# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 170, 91, 51))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/student.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 50))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 100, 91, 51))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 30, 91, 51))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/operations.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 55))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 250, 91, 51))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/detail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setShortcut("")
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, -30, 701, 391))
        self.tabWidget.setStyleSheet("font-family:helvetica;\n"
"font-size:13px")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 3, 711, 371))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 691, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit.setGeometry(QtCore.QRect(310, 60, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(160, 60, 121, 16))
        self.label.setStyleSheet("font-size:14px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 91, 16))
        self.label_2.setStyleSheet("font-size:14px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(160, 170, 91, 16))
        self.label_3.setStyleSheet("font-size:14px;")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.tab_7)
        self.comboBox.setGeometry(QtCore.QRect(310, 170, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 250, 181, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_17.setGeometry(QtCore.QRect(310, 110, 151, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 3, 701, 371))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 692, 341))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(6)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_14.setGeometry(QtCore.QRect(360, 80, 161, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_18.setGeometry(QtCore.QRect(270, 260, 111, 31))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_20 = QtWidgets.QLabel(self.tab_9)
        self.label_20.setGeometry(QtCore.QRect(170, 40, 161, 20))
        self.label_20.setStyleSheet("font-size:14px;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_9)
        self.label_21.setGeometry(QtCore.QRect(170, 120, 161, 20))
        self.label_21.setStyleSheet("font-size:14px;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_9)
        self.label_22.setGeometry(QtCore.QRect(170, 80, 161, 20))
        self.label_22.setStyleSheet("font-size:14px;")
        self.label_22.setObjectName("label_22")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_19.setGeometry(QtCore.QRect(360, 40, 161, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_23 = QtWidgets.QLabel(self.tab_9)
        self.label_23.setGeometry(QtCore.QRect(170, 160, 161, 20))
        self.label_23.setStyleSheet("font-size:14px;")
        self.label_23.setObjectName("label_23")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_5.setGeometry(QtCore.QRect(360, 200, 161, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_25 = QtWidgets.QLabel(self.tab_9)
        self.label_25.setGeometry(QtCore.QRect(170, 200, 161, 20))
        self.label_25.setStyleSheet("font-size:14px;")
        self.label_25.setObjectName("label_25")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_6.setGeometry(QtCore.QRect(360, 120, 161, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_7.setGeometry(QtCore.QRect(360, 160, 161, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_18 = QtWidgets.QLabel(self.tab_10)
        self.label_18.setGeometry(QtCore.QRect(80, 30, 151, 20))
        self.label_18.setStyleSheet("font-size:14px;")
        self.label_18.setObjectName("label_18")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_13.setGeometry(QtCore.QRect(260, 30, 161, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_17.setGeometry(QtCore.QRect(490, 30, 91, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 70, 691, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setGeometry(QtCore.QRect(60, 230, 91, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setGeometry(QtCore.QRect(180, 230, 91, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(30, 130, 191, 20))
        self.label_15.setStyleSheet("font-size:14px;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 70, 191, 20))
        self.label_16.setStyleSheet("font-size:14px;")
        self.label_16.setObjectName("label_16")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(140, 70, 161, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(30, 40, 191, 20))
        self.label_17.setStyleSheet("font-size:14px;")
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(30, 100, 191, 20))
        self.label_19.setStyleSheet("font-size:14px;")
        self.label_19.setObjectName("label_19")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 100, 161, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 130, 161, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(30, 160, 191, 20))
        self.label_24.setStyleSheet("font-size:14px;")
        self.label_24.setObjectName("label_24")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 160, 161, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setEnabled(False)
        self.label_27.setGeometry(QtCore.QRect(370, 30, 311, 20))
        self.label_27.setStyleSheet("color:red;")
        self.label_27.setObjectName("label_27")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(430, 150, 161, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setEnabled(False)
        self.label_28.setGeometry(QtCore.QRect(460, 80, 91, 21))
        self.label_28.setStyleSheet("font-size:14px;")
        self.label_28.setObjectName("label_28")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(430, 110, 161, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(340, 10, 16, 261))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 40, 161, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setGeometry(QtCore.QRect(-4, 3, 701, 371))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget_5.setGeometry(QtCore.QRect(2, 0, 692, 341))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.label_12 = QtWidgets.QLabel(self.tab_12)
        self.label_12.setGeometry(QtCore.QRect(160, 190, 191, 20))
        self.label_12.setStyleSheet("font-size:14px;")
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_10.setGeometry(QtCore.QRect(380, 140, 161, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_14.setGeometry(QtCore.QRect(290, 260, 101, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_13 = QtWidgets.QLabel(self.tab_12)
        self.label_13.setGeometry(QtCore.QRect(160, 140, 191, 20))
        self.label_13.setStyleSheet("font-size:14px;")
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_11.setGeometry(QtCore.QRect(380, 90, 161, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_14 = QtWidgets.QLabel(self.tab_12)
        self.label_14.setGeometry(QtCore.QRect(160, 90, 191, 20))
        self.label_14.setStyleSheet("font-size:14px;")
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_12.setGeometry(QtCore.QRect(380, 190, 161, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_11.setGeometry(QtCore.QRect(500, 50, 91, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_6.setGeometry(QtCore.QRect(260, 52, 161, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.tab_13)
        self.label_8.setGeometry(QtCore.QRect(70, 50, 191, 20))
        self.label_8.setStyleSheet("font-size:14px;")
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(0, 110, 701, 231))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(230, 192, 91, 26))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(350, 192, 91, 26))
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(360, 130, 161, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(150, 130, 191, 20))
        self.label_10.setStyleSheet("font-size:14px;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(150, 90, 191, 20))
        self.label_11.setStyleSheet("font-size:14px;")
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 50, 161, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(360, 90, 161, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(150, 50, 191, 20))
        self.label_9.setStyleSheet("font-size:14px;")
        self.label_9.setObjectName("label_9")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 3, 711, 371))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_14)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 60, 691, 281))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(150)
        self.label_5 = QtWidgets.QLabel(self.tab_14)
        self.label_5.setGeometry(QtCore.QRect(60, 20, 111, 16))
        self.label_5.setStyleSheet("font-size:14px;")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 20, 161, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_8.setGeometry(QtCore.QRect(410, 20, 161, 23))
        self.pushButton_8.setStyleSheet("font-size:14px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget_5.addTab(self.tab_14, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_16)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 20, 161, 23))
        self.pushButton_9.setStyleSheet("font-size:14px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_16)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 60, 691, 281))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(150)
        self.label_6 = QtWidgets.QLabel(self.tab_16)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 111, 16))
        self.label_6.setStyleSheet("font-size:14px;")
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_16)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 20, 161, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget_5.addTab(self.tab_16, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_10.setGeometry(QtCore.QRect(420, 20, 161, 23))
        self.pushButton_10.setStyleSheet("font-size:14px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 60, 691, 281))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(150)
        self.label_7 = QtWidgets.QLabel(self.tab_15)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 111, 20))
        self.label_7.setStyleSheet("font-size:14px;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 20, 161, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.tabWidget_5.addTab(self.tab_15, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(0, 338, 91, 21))
        self.label_41.setStyleSheet("background-color: rgb(147, 255, 174);\n"
"width:60px;\n"
"height:50px;\n"
"")
        self.label_41.setObjectName("label_41")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Library-Soft V2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Öğrenci Adı"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kitap Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zimmet Tarihi"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Teslim Tarihi"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Zimmet Listesi"))
        self.label.setText(_translate("MainWindow", "Öğrenci Numarası"))
        self.label_2.setText(_translate("MainWindow", "Kitap Barkodu"))
        self.label_3.setText(_translate("MainWindow", "Süre (Gün)"))
        self.comboBox.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox.setItemText(1, _translate("MainWindow", "4"))
        self.comboBox.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox.setItemText(3, _translate("MainWindow", "8"))
        self.comboBox.setItemText(4, _translate("MainWindow", "10"))
        self.comboBox.setItemText(5, _translate("MainWindow", "12"))
        self.comboBox.setItemText(6, _translate("MainWindow", "15"))
        self.pushButton_6.setText(_translate("MainWindow", "Zimmetle"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Kitap Zimmetle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Actions"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kitap Adı"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Barkod"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yayıncı"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yazar"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kategori"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Durum"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Kitap Listesi"))
        self.pushButton_18.setText(_translate("MainWindow", "Kaydet"))
        self.label_20.setText(_translate("MainWindow", "Kitap Adı"))
        self.label_21.setText(_translate("MainWindow", "Yazar"))
        self.label_22.setText(_translate("MainWindow", "Kitap Barkodu"))
        self.label_23.setText(_translate("MainWindow", "Yayıncı"))
        self.label_25.setText(_translate("MainWindow", "Kategori"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Kitap Ekle"))
        self.label_18.setText(_translate("MainWindow", "Kitap Adı veya Barkodu"))
        self.pushButton_17.setText(_translate("MainWindow", "Kitap Bul"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kitap Detaylarını Düzenle"))
        self.pushButton_15.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_16.setText(_translate("MainWindow", "Kitabı Sil"))
        self.label_15.setText(_translate("MainWindow", "Yayıncı"))
        self.label_16.setText(_translate("MainWindow", "Barkod"))
        self.label_17.setText(_translate("MainWindow", "Kitap Adı"))
        self.label_19.setText(_translate("MainWindow", "Yazarı"))
        self.label_24.setText(_translate("MainWindow", "Kategori"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Kitabı Geri Teslim Al"))
        self.label_28.setText(_translate("MainWindow", "Kitap Durumu"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Kitap Bul / Düzenle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Books"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Adı"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Numarası"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sınıfı"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Öğrenci Listesi"))
        self.label_12.setText(_translate("MainWindow", "Öğrencinin Sınıfı"))
        self.pushButton_14.setText(_translate("MainWindow", "Kaydet"))
        self.label_13.setText(_translate("MainWindow", "Öğrenci Numarası"))
        self.label_14.setText(_translate("MainWindow", "Öğrenci Adı"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Öğrenci Ekle"))
        self.pushButton_11.setText(_translate("MainWindow", "Öğrenci Bul"))
        self.label_8.setText(_translate("MainWindow", "Öğrenci Adı veya Numarası"))
        self.groupBox.setTitle(_translate("MainWindow", "Öğrenci Bilgilerini Düzenle"))
        self.pushButton_12.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_13.setText(_translate("MainWindow", "Öğrenciyi Sil"))
        self.label_10.setText(_translate("MainWindow", "Öğrencinin Sınıfı"))
        self.label_11.setText(_translate("MainWindow", "Öğrenci Numarası"))
        self.label_9.setText(_translate("MainWindow", "Öğrenci Adı"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Öğrenci Bul / Düzenle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Students"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yayıncı Adı"))
        self.label_5.setText(_translate("MainWindow", "Yayıncı Adı"))
        self.pushButton_8.setText(_translate("MainWindow", "Ekle"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), _translate("MainWindow", "Yayıncı"))
        self.pushButton_9.setText(_translate("MainWindow", "Ekle"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yazar Adı"))
        self.label_6.setText(_translate("MainWindow", "Yazar Adı"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_16), _translate("MainWindow", "Yazar"))
        self.pushButton_10.setText(_translate("MainWindow", "Ekle"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kategori Adı"))
        self.label_7.setText(_translate("MainWindow", "Kategori Adı"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_15), _translate("MainWindow", "Kategori"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Details"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a href=\"http://www.mustafakacar.com.tr\"><span style=\" text-decoration: none; color:black; font-family:helvetica; font-size:12px;\">Mustafa Kaçar</span></a></p></body></html>"))
import icons_rc
